### ISSUE TITLE
0.13.1: File to import not found or unreadable: compass/css3/box-sizing.

### ISSUE THREAD

**Issue by Eric-Guo** [tsechingho/chosen-rails#34]
Only appears at version 0.13.1, the version 0.12.0 have no below issue

``` bash
pl-form@cvprcsip01:/home/pl-form/pl-form$ rake assets:precompile
/usr/local/rvm/rubies/ruby-1.9.3-p392/bin/ruby /usr/local/rvm/gems/ruby-1.9.3-p392/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
File to import not found or unreadable: compass/css3/box-sizing.
Load paths:
  Sass::Rails::Importer(/usr/local/rvm/gems/ruby-1.9.3-p392/gems/chosen-rails-0.13.1/vendor/assets/stylesheets/chosen.css.scss)
  /usr/local/rvm/gems/ruby-1.9.3-p392/gems/anjlab-bootstrap-rails-2.3.1.2/vendor/frameworks
  (in /usr/local/rvm/gems/ruby-1.9.3-p392/gems/chosen-rails-0.13.1/vendor/assets/stylesheets/chosen.css.scss)
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/chosen-rails-0.13.1/vendor/assets/stylesheets/chosen.css.scss:1
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/sass-3.2.9/lib/sass/tree/import_node.rb:67:in `rescue in import'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/sass-3.2.9/lib/sass/tree/import_node.rb:45:in `import'
```

**Comment by adrianoresende** [comment]
Having same this issue with rails 3.2 and OS X Yosemite
