### ISSUE TITLE
error from bundle exec rake assets:precompile

### ISSUE THREAD

**Issue by Byronlee** [tsechingho/chosen-rails#64]
```
➜  krspace_platform git:(master) ✗ bundle exec rake assets:precompile
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/bundler-1.7.3/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /usr in PATH, mode 040777
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/bundler-1.7.3/lib/bundler.rb:302: warning: Insecure world writable dir /Users in PATH, mode 040777
rake aborted!
ArgumentError: wrong number of arguments (3 for 2)
  (in /Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/bundler/gems/chosen-rails-b31b58ab3226/vendor/assets/stylesheets/chosen.css.scss)
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/sass-3.2.0/lib/sass/importers/filesystem.rb:109:in `find_real_file'
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/sass-rails-4.0.3/lib/sass/rails/importer.rb:80:in `engine_from_path'
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/sass-rails-4.0.3/lib/sass/rails/importer.rb:27:in `find_relative'
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/sass-3.2.0/lib/sass/tree/import_node.rb:45:in `import'
/Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/gems/sass-3.2.0/lib/sass/tree/import_node.rb:25:in `imported_file'

```

```
ArgumentError: wrong number of arguments (3 for 2)
  (in /Users/Byronlee/.rvm/gems/ruby-2.0.0-p481/bundler/gems/chosen-rails-b31b58ab3226/vendor/assets/stylesheets/chosen.css.scss)
```
what should i do ?

**Comment by linjunzhu** [comment]
@dawidof  it works for me , thx

**Comment by EdmundMai** [comment]
`bundle update sass` didn't work for me..`sass (3.4.19)`
